version: "3.9"
services:
  app:
    build: .
    # image: "docker.nnthq.com/dashboards/capturista:0.4"
    volumes:
      - "staticfiles-volume:/app/capturista/web/static"
      - "$PWD/db.json:/app/db.json"
  web:
    image: "caddy:alpine"
    links:
      - "app"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/Caddyfile:/etc/caddy/Caddyfile"
      - "staticfiles-volume:/app/capturista/web/static"
      - "caddy_data:/data"

volumes:
  staticfiles-volume:
  caddy_data:
    external: true